version: "3.8"

services:
  squid:
    image: sameersbn/squid:latest
    container_name: squid
    restart: unless-stopped
    ports:
      - "3128:3128"  # Default HTTP proxy port
    volumes:
      - ./squid.conf:/etc/squid/squid.conf:ro
      - squid_cache:/var/spool/squid
      - squid_logs:/var/log/squid
    environment:
      - TZ=Asia/Kolkata

volumes:
  squid_cache:
  squid_logs:
